site_url: https://magic-of-christmas.netlify.app/
logo_url: https://magic-of-christmas.netlify.app/img/MagicOfChristmas-Blue-Small.png

publish_mode: editorial_workflow
backend:
  name: git-gateway
  branch: main
  squash_merges: true

media_folder: public/img
public_folder: /img

collections:
  - label: 'Component Settings'
    name: 'settings'
    files:
      - label: 'Hero Settings'
        name: 'hero'
        file: 'content/hero/settings.json'
        format: 'json'
        editor:
          preview: false
        fields:
          - {
              label: Sub Heading,
              name: subheading,
              widget: string,
              hint: 'This is used for the text under the logo',
            }
          - {
              label: Enable Button,
              name: enableButton,
              widget: boolean,
              hint: 'This is used to turn the additional book now button on or off',
            }
  - name: 'plan-your-visit'
    label: 'Plan Your Visit'
    folder: 'content/3.plan-your-visit'
    create: true
    format: 'frontmatter'
    slug: '{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - {
          label: 'Description',
          name: 'description',
          widget: 'string',
          required: false,
        }
      - { label: 'Content', name: 'body', widget: 'markdown', required: false }
  - name: 'Pages'
    label: 'Pages'
    folder: 'content'
    create: true
    format: 'frontmatter'
    slug: '{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - {
          label: 'Description',
          name: 'description',
          widget: 'string',
          required: false,
        }
      - { label: 'Content', name: 'body', widget: 'markdown', required: false }
