site_url: https://magic-of-christmas.netlify.app/
logo_url: https://magic-of-christmas.netlify.app/img/MagicOfChristmas-Blue-Small.png

publish_mode: editorial_workflow
backend:
  name: git-gateway
  branch: main
  squash_merges: true

show_preview_links: false

media_folder: public/img
public_folder: /img

collections:
  - name: 'custom'
    label: 'Custom Content'
    files:
      - label: 'Hero Settings'
        name: 'hero'
        file: 'content/site-settings/hero.json'
        format: 'json'
        editor:
          preview: false
        fields:
          - {
              label: Sub Heading,
              name: subheading,
              widget: string,
              hint: 'This is used for the text under the logo',
              required: true,
            }
          - {
              label: Enable Button,
              name: enableButton,
              widget: boolean,
              hint: 'This is used to turn the additional book now button on or off',
            }
      - label: 'FAQs'
        name: 'faqs'
        file: 'content/plan-your-visit/_faq-items.json'
        format: 'json'
        widget: 'list'
        allow_add: true
        summary: '{{fields.category}} - {{fields.question}}'
        fields:
          - label: Frequently Asked Question
            name: frequently-asked-question
            widget: object
            fields:
              - {
                  label: Category,
                  name: category,
                  widget: select,
                  options: ['Big Top Theatre', 'Performance', 'Tickets'],
                  default: 'Big Top Theatre',
                  required: true,
                }
              - {
                  label: Question,
                  name: question,
                  widget: string,
                  required: true,
                }
              - { label: Answer, name: answer, widget: string, required: true }
      - label: 'About'
        name: 'about'
        file: 'content/about.json'
        format: 'frontmatter'
        fields:
          - { label: 'Title', name: 'title', widget: 'string', required: true }
          - {
              label: 'Description',
              name: 'description',
              widget: 'string',
              required: false,
            }
          - {
              label: 'Image 1',
              name: 'aboutImg1',
              widget: 'image',
              required: true,
            }
          - {
              label: 'Image 2',
              name: 'aboutImg2',
              widget: 'image',
              required: true,
            }
          - {
              label: 'Image 3',
              name: 'aboutImg3',
              widget: 'image',
              required: true,
            }
          - {
              label: 'Image 4',
              name: 'aboutImg4',
              widget: 'image',
              required: true,
            }
          - {
              label: 'Image 5',
              name: 'aboutImg5',
              widget: 'image',
              required: true,
            }
          - {
              label: 'Content',
              name: 'body',
              widget: 'markdown',
              required: false,
            }

  - name: 'Pages'
    label: 'Pages'
    folder: 'content'
    create: true
    format: 'frontmatter'
    filter: { field: 'customPage', value: false }
    slug: '{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - {
          label: 'Description',
          name: 'description',
          widget: 'string',
          required: false,
        }
      - { label: 'Content', name: 'body', widget: 'markdown', required: false }

  - name: 'plan-your-visit'
    label: 'Plan Your Visit'
    folder: 'content/plan-your-visit'
    create: true
    format: 'frontmatter'
    filter: { field: 'customPage', value: false }
    slug: '{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - {
          label: 'Description',
          name: 'description',
          widget: 'string',
          required: false,
        }
      - { label: 'Content', name: 'body', widget: 'markdown', required: false }

  - name: 'legal'
    label: 'Legal'
    folder: 'content/legal'
    create: true
    format: 'frontmatter'
    filter: { field: 'customPage', value: false }
    slug: '{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - {
          label: 'Description',
          name: 'description',
          widget: 'string',
          required: false,
        }
      - { label: 'Content', name: 'body', widget: 'markdown', required: false }
