site_url: https://magic-of-christmas.netlify.app/
logo_url: https://magic-of-christmas.netlify.app/img/MagicOfChristmas-Blue-Small.png

publish_mode: editorial_workflow
backend:
  name: git-gateway
  branch: main
  squash_merges: true

show_preview_links: false

media_folder: public/img
public_folder: /img

collections:
  - name: 'settings'
    label: 'Component Settings'
    files:
      - label: 'Hero Settings'
        name: 'hero'
        file: 'content/site-settings/hero.json'
        format: 'json'
        editor:
          preview: false
        fields:
          - {
              label: Sub Heading,
              name: subheading,
              widget: string,
              hint: 'This is used for the text under the logo',
            }
          - {
              label: Enable Button,
              name: enableButton,
              widget: boolean,
              hint: 'This is used to turn the additional book now button on or off',
            }
  - name: 'faq'
    label: 'Frequently Asked Questions'
    files:
      - label: 'FAQs'
        name: 'faqs'
        file: 'content/plan-your-visit/_faq-items.json'
        format: 'json'
        editor:
          preview: false
        widget: 'list'
        allow_add: true
        summary: '{{fields.category}} - {{fields.question}}'
        fields:
          - {
              label: Category,
              name: category,
              widget: select,
              options: ['Big Top Theatre', 'Performance', 'Tickets'],
              default: 'Big Top Theatre',
            }
          - { label: Question, name: question, widget: string }
          - { label: Answer, name: answer, widget: string }
  - name: 'Pages'
    label: 'Pages'
    folder: 'content'
    create: true
    format: 'frontmatter'
    slug: '{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - {
          label: 'Description',
          name: 'description',
          widget: 'string',
          required: false,
        }
      - { label: 'Content', name: 'body', widget: 'markdown', required: false }

  - name: 'plan-your-visit'
    label: 'Plan Your Visit'
    folder: 'content/plan-your-visit'
    create: true
    format: 'frontmatter'
    slug: '{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - {
          label: 'Description',
          name: 'description',
          widget: 'string',
          required: false,
        }
      - { label: 'Content', name: 'body', widget: 'markdown', required: false }
  - name: 'legal'
    label: 'Legal'
    folder: 'content/legal'
    create: true
    format: 'frontmatter'
    slug: '{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - {
          label: 'Description',
          name: 'description',
          widget: 'string',
          required: false,
        }
      - { label: 'Content', name: 'body', widget: 'markdown', required: false }
