site_url: https://magic-of-christmas.netlify.app/
logo_url: https://magic-of-christmas.netlify.app/img/MagicOfChristmas-Blue-Small.png

publish_mode: editorial_workflow
backend:
  name: git-gateway
  branch: master
  squash_merges: true

media_folder: public/img
public_folder: /img

collections:
  - name: 'plan-your-visit'
    label: 'Plan Your Visit'
    folder: 'content/plan-your-visit'
    create: true
    format: 'frontmatter'
    slug: '{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - {
          label: 'Description',
          name: 'description',
          widget: 'string',
          required: false,
        }
      - { label: 'Content', name: 'body', widget: 'markdown', required: false }
  - name: 'Pages'
    label: 'Pages'
    folder: 'content'
    create: true
    format: 'frontmatter'
    slug: '{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - {
          label: 'Description',
          name: 'description',
          widget: 'string',
          required: false,
        }
      - { label: 'Content', name: 'body', widget: 'markdown', required: false }
